info:
    component: Zuul Server

spring:
  profiles: cloud
  application:
     name: ROOMZUULAPIGATEWAY

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

zuul:
    routes:
        ROOMSERVICECONSUMER:
            path: /Consumer/**
        ROOMSERVICEPRODUCER:
            path: /Producer/**

server:
  port: 8765
  
eureka:
    us-west-2:
        availabilityZones: us-west-2a, us-west-2b
    client:
        register-with-eureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://ec2-34-218-221-120.us-west-2.compute.amazonaws.com/eureka/
            us-west-2a: http://ec2-34-218-221-120.us-west-2.compute.amazonaws.com/eureka/
            us-west-2b: http://ec2-34-218-221-120.us-west-2.compute.amazonaws.com/eureka/
        
